[workspace]
members = [
    "bin/*",
    "programs/mango-v4",
    "lib/*",
]

[workspace.dependencies]
anchor-client = { git = "https://github.com/coral-xyz/anchor.git", rev = "2af9cc669", version = "0.28.0" }
anchor-lang = { git = "https://github.com/coral-xyz/anchor.git", rev = "2af9cc669", version = "0.28.0" }
anchor-spl = { git = "https://github.com/coral-xyz/anchor.git", rev = "2af9cc669", version = "0.28.0" }
fixed = { git = "https://gitlab.com/ckamm/fixed.git", branch = "v1.11.0-mango" }
pyth-sdk-solana = "0.8.0"
serum_dex = { git = "https://github.com/openbook-dex/program.git" }
solana-address-lookup-table-program = "~1.16.1"
solana-account-decoder = "~1.16.1"
solana-client = "~1.16.1"
solana-logger = "~1.16.1"
solana-program = "~1.16.1"
solana-program-test = "~1.16.1"
solana-rpc = "~1.16.1"
solana-sdk = "~1.16.1"

[profile.release]
overflow-checks = true

[patch.crates-io]
# for gzip encoded responses
jsonrpc-core-client = { git = "https://github.com/ckamm/jsonrpc.git", branch = "ckamm/http-with-gzip" }
